#157 adds warning when global fixture is called
canjs/can-fixture pull request #165
Opened 2019-04-05 18:12 UTC by Amechi101

For issue #157 adds warning for when global window fixture. But current test not currently running likely due to some other test failing. The test currently added works in isolation but when ran amongst other test it fails.

2019-04-05 18:18 UTC, cherifGsoul commented on fixture.js
> +		debugger
You forget `debugger` statement.

2019-04-05 18:19 UTC, cherifGsoul commented on test/fixture_test.js
> +	debugger
Another `debugger` statement here.

2019-04-05 18:22 UTC, cherifGsoul commented on fixture.js
> +	// window.fixture = fixture;
I'd remove this comment.

2019-04-05 18:24 UTC, cherifGsoul requested changes
Thank you for this, I added some comments.

2019-04-29 20:09 UTC, chasenlehara approved these changes

2019-05-01 20:12 UTC, merged